#!/usr/bin/env bash

receive_pipe="/tmp/waybar-laptop-brightness-module-rx"
step=2

rm -rf "$receive_pipe"
mkfifo "$receive_pipe"

print_brightness() {
  if brightness=$("$@"); then
    brightness=$(echo "$brightness" | cut -d ',' -f4 | tr -d '%')
  else
    brightness=-1
  fi
  echo "{ \"text\": \"$brightness\", \"tooltip\": \"Laptop monitor: $brightness%\" }"
}

# main brightnessctl command
brightnessctl_command() {
  brightnessctl -m "$@"
}

# in case waybar restarted the script after restarting/replugging a monitor
print_brightness brightnessctl_command

while true; do
  read -r command < "$receive_pipe"
  case $command in
    +)
      print_brightness brightnessctl_command set +"$step"%
      ;;
    -)
      print_brightness brightnessctl_command set "$step"%-
      ;;
    max)
      print_brightness brightnessctl_command set 100%
      ;;
    min)
      print_brightness brightnessctl_command set 1
      ;;
  esac
  print_brightness brightnessctl_command
done
