#!/usr/bin/env sh

while true; do
    ping=$(ping -q -w 3 -c 1 1.1.1.1 | tail -n1 | cut -d '/' -f 5 | awk -F. '{print $1}' | tr -d '\n')

    if [ "$(expr "$ping" : "[0-9]*$")" -eq 0 ]; then
        printf '{"text": "", "tooltip": "Ping: failing or > 3000ms", "class": "failing"}\n'
    elif [ "$ping" -lt 25 ]; then
        printf '{"text": "", "tooltip": "Ping: %s ms", "class": "fast"}\n' "$ping"
    elif [ "$ping" -lt 100 ]; then
        printf '{"text": "", "tooltip": "Ping: %s ms", "class": "normal"}\n' "$ping"
    else
        printf '{"text": "", "tooltip": "Ping: %s ms", "class": "slow"}\n' "$ping"
    fi
    sleep 8
done
